// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package kr.swmaestro.hsb.model;

import java.lang.String;

privileged aspect ResultModel_Roo_JavaBean {
    
    public String ResultModel.getMom() {
        return this.mom;
    }
    
    public void ResultModel.setMom(String mom) {
        this.mom = mom;
    }
    
}
