// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package kr.swmaestro.hsb.model;

import java.lang.String;

privileged aspect RooTestModel_Roo_JavaBean {
    
    public String RooTestModel.getMsg() {
        return this.msg;
    }
    
    public void RooTestModel.setMsg(String msg) {
        this.msg = msg;
    }
    
}
